---
title: "Ikea"
author: "JFlynn"
date: "11/3/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

ikea <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-11-03/ikea.csv')


```


```{r}

library(tidyverse)
library(scales)

```


```{r}

theme_jf <- function(background = '#ffffff') {
  
  theme(plot.background = element_rect(fill = background, colour = NA),
        strip.text = element_blank(), 
        axis.text = element_text(margin = ggplot2::margin(0, 0, 0, 10), 
                                 colour = colorspace::darken("#2a3b56", 0.3), 
                                 size = 12), 
        
        plot.title = element_text(hjust = 0.5, size = 20, 
                                  colour = "#2a3b56"), 
        plot.subtitle = element_text(hjust = 0.5, size = 12, 
                                     margin = ggplot2::margin(10, 0, 0, 0), 
                                     colour = colorspace::lighten("#2a3b56", 0.3)), 
        plot.caption = element_text(colour = "#2a3b56", size = 10, 
                                    margin = ggplot2::margin(20, 0, 0, 0)), 
        plot.margin = ggplot2::margin(20, 20, 20, 20))
}

```


```{r}

ggplot(ikea) + 
        aes(width, height, alpha = depth, 
            color = category) + 
        geom_point()

```





```{r}

reg <- 'units|& drawer units|buffets &'

ikea <- ikea %>% 
        mutate(category = str_replace_all(ikea$category, reg, ''))

```



```{r}

ikea %>% 
        group_by(category) %>% 
        count() %>% 
        arrange(desc(n)) %>% 
        gt::gt()

```


```{r}

ikea %>% 
        ggplot() + 
        aes(xmin = 0, xmax = width, 
            ymin = 0, ymax = height, 
            alpha = depth, 
            group = item_id) + 
        geom_rect(fill = 'grey98', 
            color = '#2a3b56', 
            show.legend = FALSE) + 
  geom_text(aes(x = 200, y = 550,
                label = category),
            vjust = "top", size = 3.4, 
            show.legend = FALSE, 
            color = "#2a3b56") +
        theme_void() + 
        theme_jf() + 
        theme(axis.text = element_text(size = 8)) +
        facet_wrap(~category) +
        scale_y_continuous(labels = label_comma(suffix = ' cm')) +
        scale_x_continuous(labels = label_comma(suffix = ' cm')) +
        labs(title = 'Ikea Furniture Size', 
             caption = 'Data: fivethirtyeight | Graphic: J Flynn')
        

```

```{r}

ggsave(here::here("ikea.png"), 
       dpi = 320, width = 7,
       height = 7)

```

